name: $(major).$(minor).$(revision)$(Rev:.r)
trigger:
- main

variables:
  agentSolution: 'src/Agent.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 5
  minor: 0
  revision: 0
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadSecureFile@1
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'loupe.agent.snk'
      overWrite: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'loupe.agent.snk'
      TargetFolder: '$(Build.SourcesDirectory)'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(agentSolution)'

  - task: VSBuild@1
    inputs:
      solution: '$(agentSolution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:CustomVersion=$(fileVersion)'
  
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src'
      contents: 'agent/**/(*.nupkg|*.snupkg)'
      flattenFolders: true
      targetFolder: '$(Build.ArtifactStagingDirectory)/packages'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **/bin/Release/Loupe.Agent.Test.dll
      searchFolder: '$(Build.SourcesDirectory)'
      vsTestVersion: '17.0'
      codeCoverageEnabled: true